# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils")
env.LoadableModuleIncomplete("_baseLib", Split("baseLib.i"), LIBS=env.getlibs("daf_base pex_exceptions"))
