# -*- python -*-
import re
Import("env")

pkg = env["eups_product"]
env.CheckSwig("python", ilang="c++", includedProducts="utils pex_exceptions")
env.LoadableModuleIncomplete("_baseLib", Split("baseLib.i"),
                             CCFLAGS=re.sub("-Wall", "", " ".join(env['CCFLAGS'])),
                             LIBS=env.getlibs(pkg))
