# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(['dateTime/dateTime', 'persistable',
	'propertyContainer/propertyList', 'propertyContainer/propertySet'], addUnderscore=False)
