# -*- python -*-
Import("env")

env.Program(["DataProperty_1.cc"], LIBS=env.libs["boost"] + ["daf_base"])
env.Program(["DataProperty_2.cc"], LIBS=env.libs["boost"] + ["daf_base"])
env.Program(["DataProperty_4.cc"], LIBS=env.libs["boost"] + ["daf_base"])

env.CheckSwig("python", ilang="c++")
env.Append(SWIGFLAGS=" -Ipython")

#
# Tests
#
# import lsst.tests

# tests.run("DataProperty_*.cc")

# for target in tests.run("*.py"):
#     env.Depends(target,
#         "../python/lsst/daf/base/_baseLib%s" % (mod, env['LDMODULESUFFIX']))
