# -*- python -*-
Import("env")

env.Program(["PropertySet_1.cc"], LIBS=env.libs["daf_base"])

env.CheckSwig("python", ilang="c++")
env.Append(SWIGFLAGS=" -Ipython")

#
# Tests
#
import lsst.tests

tests = lsst.tests.Control(env, verbose = True)
tests.run("PropertySet_*.cc")

for target in tests.run("*.py"):
     env.Depends(target,
        "../python/lsst/daf/base/_baseLib%s" % (env['LDMODULESUFFIX']))
