# -*- python -*-
Import('env')
import os

env.SharedLibrary('daf_base',
                         map(lambda str: "../src/" + str,
                            ["Citizen.cc",
                             "DateTime.cc",
                             "Persistable.cc",
                             "PropertySet.cc"
                            ]), LIBS=env.getlibs("boost utils"))

