# -*- python -*-
Import('env')

env.Program("citizen", ["citizen.cc"],
    LIBS=env.getlibs("daf_base utils pex_exceptions"))

#
# Tests
#
import lsst.tests
tests = lsst.tests.Control(env, verbose=True)

if tests.runExamples:
    tests.run("*.cc")
    tests.run("*.py")
